# Generated by Django 3.0.2 on 2020-02-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('overview', models.TextField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('amenities', models.CharField(max_length=250, null=True)),
                ('besttime', models.CharField(max_length=150, null=True)),
                ('howtoreach', models.CharField(max_length=250, null=True)),
                ('nativelang', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('mainphoto', models.CharField(max_length=25, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
