# Generated by Django 3.0.2 on 2020-03-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200306_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemembers',
            name='status',
        ),
        migrations.AlterField(
            model_name='committeemembers',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
