# Generated by Django 3.0.2 on 2020-03-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200306_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=7),
        ),
    ]
