# Generated by Django 3.0.2 on 2020-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200306_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='judge',
            field=models.IntegerField(null=True),
        ),
    ]
