# Generated by Django 3.0.2 on 2020-03-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_programsapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='committee_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.CommitteeMembers'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Judges'),
        ),
        migrations.AlterField(
            model_name='programsapplied',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Candidates'),
        ),
        migrations.AlterField(
            model_name='programsapplied',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Programs'),
        ),
    ]
