# Generated by Django 3.0.2 on 2020-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20200306_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='published',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=7),
        ),
        migrations.AddField(
            model_name='programsapplied',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programsapplied',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=7),
        ),
        migrations.AddField(
            model_name='results',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=7),
        ),
    ]
