# Generated by Django 3.0.2 on 2020-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20200306_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='remarks',
            field=models.TextField(default='', null=True),
        ),
    ]
